### ISSUE TITLE
Task 8

### ISSUE THREAD

**Issue by AntonGrigoriev** [ypldan/Student-Practice#3]
@ypldan 

**response**
* Для отправки данных можно использовать метод res.send(), который вызывает res.end() внутри себя. К тому же, этому методу можно передавать объект без JSON.stringify(), так как это тоже происходит внутри.

**Форматирование кода**
* Часто используете двойные ковычки для строк. Стоит всегда использовать одинарные.

**Comment by ypldan** [comment]
Окей, улічу на будучыню, дзякуй.
